version: '3.8'

services:
  ohdsi-webapi-mcp:
    build: .
    environment:
      - WEBAPI_BASE_URL=${WEBAPI_BASE_URL:-https://atlas-demo.ohdsi.org/WebAPI}
      # Uncomment if you need cohort size estimation:
      # - WEBAPI_SOURCE_KEY=${WEBAPI_SOURCE_KEY:-EUNOMIA}
    stdin_open: true
    tty: true
    volumes:
      # Mount local development code (for development)
      - ./src:/app/src:ro
    profiles:
      - dev

  # Production service (without volume mounts)
  ohdsi-webapi-mcp-prod:
    build: .
    environment:
      - WEBAPI_BASE_URL=${WEBAPI_BASE_URL}
      # Uncomment if you need cohort size estimation:
      # - WEBAPI_SOURCE_KEY=${WEBAPI_SOURCE_KEY}
    stdin_open: true
    tty: true
